spring:
    datasource.url: jdbc:h2:mem:mydb
    h2.console:
        enabled: true
        path: /console

server:
  port: 8443
  http.port: 8080
  ssl:
    key-store: src/main/resources/ssl/keystore.p12
    key-store-password: mypassword
    keyStoreType: PKCS12
    keyAlias: myselfsigned